backend: "openvino"
output: [
  {
    name: "softmax_tensor"
    data_type: TYPE_FP32
    dims: [ -1, 1001]
  }
]
parameters: [
{
   key: "NUM_STREAMS"
   value: {
     string_value: "1"
   }
},
{
   key: "PERFORMANCE_HINT"
   value: {
     string_value: "LATENCY"
   }
}
]
default_model_filename: "model.pb"
